--- #YAML:1.0
name:                Template-Plugin-JSON
version:             0.03
abstract:            ~
license:             ~
generated_by:        ExtUtils::MakeMaker version 6.32
distribution_type:   module
requires:     
    Template::Plugin::VMethods:    0.03
    Test::More:                    0
    Test::use::ok:                 0
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.2.html
    version: 1.2
