# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Template-Plugin-JSON
version:      0.01
version_from: lib/Template/Plugin/JSON.pm
installdirs:  site
requires:
    Template::Plugin::VMethods:    0.03
    Test::More:                    0
    Test::use::ok:                 0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30
